// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5FHlRoSHu6USAJHznWXYb_WL-wQ6IxY',
    appId: '1:726007170976:web:b18f7f82b9fdc57da646c5',
    messagingSenderId: '726007170976',
    projectId: 'quizy-4d9bf',
    authDomain: 'quizy-4d9bf.firebaseapp.com',
    storageBucket: 'quizy-4d9bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF62QULVPJw56z7JM_ya0puE-n_5DMaK4',
    appId: '1:726007170976:android:5141c68da7ff0d8fa646c5',
    messagingSenderId: '726007170976',
    projectId: 'quizy-4d9bf',
    storageBucket: 'quizy-4d9bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACDahEcrrpWdniza8al-K-9mQGz9Dptdc',
    appId: '1:726007170976:ios:aacc0324fe8890bfa646c5',
    messagingSenderId: '726007170976',
    projectId: 'quizy-4d9bf',
    storageBucket: 'quizy-4d9bf.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACDahEcrrpWdniza8al-K-9mQGz9Dptdc',
    appId: '1:726007170976:ios:aacc0324fe8890bfa646c5',
    messagingSenderId: '726007170976',
    projectId: 'quizy-4d9bf',
    storageBucket: 'quizy-4d9bf.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5FHlRoSHu6USAJHznWXYb_WL-wQ6IxY',
    appId: '1:726007170976:web:44069e0cc8004c67a646c5',
    messagingSenderId: '726007170976',
    projectId: 'quizy-4d9bf',
    authDomain: 'quizy-4d9bf.firebaseapp.com',
    storageBucket: 'quizy-4d9bf.firebasestorage.app',
  );

}